In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect("../data/master_quant_database.db")
df = pd.read_sql_query("SELECT * FROM UNIFIED_RESEARCH_MATRIX", conn)

In [3]:
df.head(5)

,ticker,date,open,high,low,close,volume,pct,vol_pct,ratio_event,...,Magnitude_NLP,Impact_Force,rsi,sma_50,bb_width,atr_pct,vol_ma20,ema_200,dist_ema200,MACD_hist
0,AAA,2016-02-22 00:00:00,7.37,7.34,7.20,7.25,173963.0,-0.012262,0.436468,1.0,...,0.10,0.009677,62.820513,6.4436,0.152973,3.467980,442724.90,5.898306,0.229166,-0.019567
1,AAA,2016-02-23 00:00:00,7.32,7.29,7.10,7.10,251510.0,-0.020690,1.445767,1.0,...,0.35,0.087500,56.024096,6.4760,0.152973,3.098592,439999.85,5.910263,0.201300,-0.033549
2,AAA,2016-02-24 00:00:00,7.17,7.20,7.05,7.15,306984.0,0.007042,1.220564,1.0,...,0.00,0.000000,56.024096,6.5074,0.152952,2.977023,414252.85,5.922599,0.207240,-0.039366
3,AAA,2016-02-25 00:00:00,7.27,7.39,7.15,7.20,278800.0,0.006993,0.908191,1.0,...,0.80,-0.240000,69.014085,6.5408,0.136884,2.708333,384347.10,5.935309,0.213079,-0.039671
4,AAA,2016-02-26 00:00:00,7.27,7.25,7.10,7.15,147340.0,-0.006944,0.528479,1.0,...,0.10,0.000000,58.474576,6.5760,0.123524,2.587413,371843.60,5.947396,0.202207,-0.042796

In [4]:
testing_data = df.loc[:,['ticker', 'date', 'adj_open', 'adj_high', 'adj_low', 'adj_close', 'volume']]
testing_data.head(5)

,ticker,date,adj_open,adj_high,adj_low,adj_close,volume
0,AAA,2016-02-22 00:00:00,7.37,7.34,7.20,7.25,173963.0
1,AAA,2016-02-23 00:00:00,7.32,7.29,7.10,7.10,251510.0
2,AAA,2016-02-24 00:00:00,7.17,7.20,7.05,7.15,306984.0
3,AAA,2016-02-25 00:00:00,7.27,7.39,7.15,7.20,278800.0
4,AAA,2016-02-26 00:00:00,7.27,7.25,7.10,7.15,147340.0

In [5]:
testing_data['date'] = pd.to_datetime(testing_data['date'])
testing_data['date']

0        2016-02-22
1        2016-02-23
2        2016-02-24
3        2016-02-25
4        2016-02-26
            ...
843206   2026-04-08
843207   2026-04-09
843208   2026-04-10
843209   2026-04-13
843210   2026-04-14
Name: date, Length: 843211, dtype: datetime64[us]

In [6]:
# Only include the data for VN30 universe (in 1/2024)
universe = [
    'ACB', 'BCM', 'BID', 'BVH', 'CTG',
    'FPT', 'GAS', 'GVR', 'HDB', 'HPG',
    'MBB', 'MSN', 'MWG', 'PLX', 'POW',
    'SAB', 'SHB', 'SSB', 'SSI', 'STB',
    'TCB', 'TPB', 'VCB', 'VHM', 'VIB',
    'VIC', 'VJC', 'VNM', 'VPB', 'VRE'
]
data = {}
for ticker in universe:
    dat = testing_data[testing_data['ticker'] == ticker]
    dat = dat.loc[:, ['date', 'adj_open', 'adj_high', 'adj_low', 'adj_close', 'volume']]
    dat.set_index('date', inplace=True)
    data[ticker] = dat

In [7]:
len(data), data['ACB'].head(5)

(30,
             adj_open  adj_high  adj_low  adj_close    volume
 date
 2016-02-22      3.01      3.09     3.01       3.05   93741.0
 2016-02-23      3.06      3.09     3.05       3.05  268334.0
 2016-02-24      2.89      3.20     2.89       3.17  613706.0
 2016-02-25      3.28      3.43     3.13       3.14  170309.0
 2016-02-26      3.14      3.16     3.13       3.16   54693.0)

In [8]:
for ticker, datum in data.items():
    print(ticker, datum.index.min())

ACB 2016-02-22 00:00:00
BCM 2018-07-23 00:00:00
BID 2016-04-22 00:00:00
BVH 2016-04-22 00:00:00
CTG 2016-05-17 00:00:00
FPT 2016-05-04 00:00:00
GAS 2016-04-22 00:00:00
GVR 2018-08-10 00:00:00
HDB 2018-06-07 00:00:00
HPG 2016-02-22 00:00:00
MBB 2016-02-22 00:00:00
MSN 2016-02-22 00:00:00
MWG 2016-02-22 00:00:00
PLX 2017-09-12 00:00:00
POW 2018-07-26 00:00:00
SAB 2017-05-05 00:00:00
SHB 2016-08-24 00:00:00
SSB 2021-08-13 00:00:00
SSI 2016-05-06 00:00:00
STB 2016-02-22 00:00:00
TCB 2018-10-22 00:00:00
TPB 2018-09-11 00:00:00
VCB 2016-04-22 00:00:00
VHM 2018-10-08 00:00:00
VIB 2017-06-07 00:00:00
VIC 2016-05-05 00:00:00
VJC 2017-07-20 00:00:00
VNM 2016-04-22 00:00:00
VPB 2018-01-05 00:00:00
VRE 2018-04-09 00:00:00

In [9]:
true_calendar = data['ACB'].index
for ticker, datum in data.items():
    true_calendar = true_calendar.union(datum.index)
print(len(true_calendar))
data['ACB'].reindex(true_calendar, method='pad')

2537

            adj_open  adj_high  adj_low  adj_close      volume
date
2016-02-22      3.01      3.09     3.01       3.05     93741.0
2016-02-23      3.06      3.09     3.05       3.05    268334.0
2016-02-24      2.89      3.20     2.89       3.17    613706.0
2016-02-25      3.28      3.43     3.13       3.14    170309.0
2016-02-26      3.14      3.16     3.13       3.16     54693.0
...              ...       ...      ...        ...         ...
2026-04-08     23.70     24.15    23.55      24.10  19727300.0
2026-04-09     24.05     24.05    23.75      23.85   5141500.0
2026-04-10     24.10     24.20    23.85      23.85   8136300.0
2026-04-13     23.80     24.00    23.55      23.75   8083900.0
2026-04-14     23.95     24.15    23.80      24.00  15449600.0

[2537 rows x 5 columns]

In [10]:
for ticker in data:
    data[ticker] = data[ticker].reindex(true_calendar, method='pad')

In [11]:
cal = true_calendar
week = pd.date_range('2020-12-02', '2020-12-08', freq='B')  # Wed..Tue, 5 business days
n = sum(1 for t,df in data.items() if week.isin(df.index).all())
print('tickers having ALL of 2020-12-02..08:', n, '/', len(data))
print('  (calendar has', sum(1 for d in week if d in cal), 'of those 5 days)')
for d in ['2018-01-23','2018-01-24']:
    ts = pd.Timestamp(d)
    n = sum(1 for t,df in data.items() if ts not in df.index)
    print(f'{d}: missing from {n}/30 tickers')

tickers having ALL of 2020-12-02..08: 30 / 30
  (calendar has 5 of those 5 days)
2018-01-23: missing from 0/30 tickers
2018-01-24: missing from 0/30 tickers

In [12]:
import pickle
with open('../data/vn30_ohlcv.pickle', 'wb') as f:
    pickle.dump(data, f)

In [13]:
with open('../data/trading_date.pickle', 'wb') as f:
    pickle.dump(true_calendar, f)

In [14]:
import pickle

import pandas as pd

with open('/home/supperman/Projects/quant/src/data/trading_date.pickle', 'rb') as f:
    trading_days = pickle.load(f)  # canonical calendar, 2532 days

with open('/home/supperman/Projects/quant/src/data/vn30_ohlcv.pickle', 'rb') as f:
    data = pickle.load(f)


def gap_episodes(missing, calendar):
    """Group missing dates into consecutive-trading-day runs.

    Consecutive positions in the canonical calendar = one episode
    (a suspension stretch), so Friday->Monday gaps count as one episode.
    """
    if len(missing) == 0:
        return []
    pos = calendar.get_indexer(missing)
    episodes, start = [], pos[0]
    for i in range(1, len(pos)):
        if pos[i] != pos[i - 1] + 1:  # break in consecutive positions
            episodes.append((calendar[start], calendar[pos[i - 1]]))
            start = pos[i]
    episodes.append((calendar[start], calendar[pos[-1]]))
    return episodes


rows = []
for ticker, df in data.items():
    idx = df.index
    first, last = idx.min(), idx.max()
    expected = trading_days[(trading_days >= first) & (trading_days <= last)]
    missing = expected.difference(idx)
    episodes = gap_episodes(missing, trading_days)
    rows.append({
        'ticker': ticker,
        'rows': len(idx),
        'first': first.date(),
        'last': last.date(),
        'expected': len(expected),
        'internal_gaps': len(missing),
        'episodes': len(episodes),
        'longest_episode_days': max((e[1] - e[0]).days + 1 for e in episodes) if episodes else 0,
        'extra_dates': len(idx.difference(trading_days)),   # rows on non-trading days
        'duplicates': int(idx.duplicated().sum()),
        'monotonic': bool(idx.is_monotonic_increasing),
    })

res = pd.DataFrame(rows).sort_values('internal_gaps', ascending=False)
print(res.to_string(index=False))

print("\n=== tickers with internal gaps: %d of %d ===" %
      ((res['internal_gaps'] > 0).sum(), len(res)))
print("=== any index anomalies (extra dates / duplicates / non-monotonic)? ===")
anom = res[(res['extra_dates'] > 0) | (res['duplicates'] > 0) | (~res['monotonic'])]
print(anom.to_string(index=False) if len(anom) else "none")

# Show the worst ticker's episodes in detail
worst = res.iloc[0]
ticker = worst['ticker']
missing = trading_days[
    (trading_days >= pd.Timestamp(worst['first'])) &
    (trading_days <= pd.Timestamp(worst['last']))
].difference(data[ticker].index)
eps = gap_episodes(missing, trading_days)
print(f"\n=== longest episodes for {ticker} ({len(eps)} episodes, "
      f"{len(missing)} missing days) ===")
for start, end in sorted(eps, key=lambda e: (e[1] - e[0]).days, reverse=True)[:8]:
    print(f"  {start.date()} -> {end.date()}  ({(end - start).days + 1} calendar days, "
          f"{len(trading_days[(trading_days >= start) & (trading_days <= end)])} trading days)")

ticker  rows      first       last  expected  internal_gaps  episodes  longest_episode_days  extra_dates  duplicates  monotonic
   ACB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   BCM  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   BID  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   BVH  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   CTG  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   FPT  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   GAS  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   GVR  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   HDB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   HPG  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   MBB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   MSN  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   MWG  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   PLX  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   POW  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   SAB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   SHB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   SSB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   SSI  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   STB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   TCB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   TPB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VCB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VHM  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VIB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VIC  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VJC  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VNM  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VPB  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True
   VRE  2537 2016-02-22 2026-04-14      2537              0         0                     0            0           0       True

=== tickers with internal gaps: 0 of 30 ===
=== any index anomalies (extra dates / duplicates / non-monotonic)? ===
none

=== longest episodes for ACB (0 episodes, 0 missing days) ===

In [15]:
# Avg. trading days. Instead of just trusting some rando yapping about a market that isn't ours, just calculate it.
r = data['ACB'].resample("1YE")
r

In [16]:
r.count()

            adj_open  adj_high  adj_low  adj_close  volume
date
2016-12-31       221       221      221        221     221
2017-12-31       250       250      250        250     250
2018-12-31       250       250      250        250     250
2019-12-31       250       250      250        250     250
2020-12-31       252       252      252        252     252
2021-12-31       250       250      250        250     250
2022-12-31       249       249      249        249     249
2023-12-31       249       249      249        249     249
2024-12-31       250       250      250        250     250
2025-12-31       249       249      249        249     249
2026-12-31        67        67       67         67      67

In [17]:
# Close to 250. Fluctuations due to Lunar New Year.

In [18]:
data['ACB']['adj_close'][data['ACB']['adj_close'].isna()].count()

np.int64(0)

In [19]:
for ticker, datum in data.items():
    print(ticker, datum['adj_open'][datum['adj_open'].isna()].count())

ACB 0
BCM 0
BID 0
BVH 0
CTG 0
FPT 0
GAS 0
GVR 0
HDB 0
HPG 0
MBB 0
MSN 0
MWG 0
PLX 0
POW 0
SAB 0
SHB 0
SSB 0
SSI 0
STB 0
TCB 0
TPB 0
VCB 0
VHM 0
VIB 0
VIC 0
VJC 0
VNM 0
VPB 0
VRE 0

In [20]:
data['ACB']["2020-12-01":"2020-12-10"]

            adj_open  adj_high  adj_low  adj_close      volume
date
2020-12-01     10.21     10.24    10.06      10.24   9249711.0
2020-12-02     10.21     10.24    10.06      10.24   9249711.0
2020-12-03     10.21     10.24    10.06      10.24   9249711.0
2020-12-04     10.21     10.24    10.06      10.24   9249711.0
2020-12-07     10.21     10.24    10.06      10.24   9249711.0
2020-12-08     10.21     10.24    10.06      10.24   9249711.0
2020-12-09     10.54     10.86    10.43      10.71  24200930.0
2020-12-10     10.81     10.81    10.47      10.49   9233750.0

In [21]:
data['PLX']["2020-12-01":"2020-12-10"]

            adj_open  adj_high  adj_low  adj_close     volume
date
2020-12-01     42.99     43.68    42.56      43.50   907360.0
2020-12-02     43.50     44.19    42.99      43.76   632830.0
2020-12-03     44.11     44.11    43.25      43.50   688180.0
2020-12-04     43.76     44.36    43.50      43.68   901290.0
2020-12-07     44.19     44.19    43.85      44.11   534840.0
2020-12-08     44.11     44.19    43.50      43.59   768990.0
2020-12-09     43.76     45.57    43.59      44.97  1540750.0
2020-12-10     44.97     45.57    44.36      44.36   906890.0